import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { 
  ArrowLeft, 
  ArrowRight, 
  BarChart3,
  Shield, 
  AlertTriangle, 
  CheckCircle, 
  TrendingUp,
  DollarSign,
  Users,
  Lock,
  Eye,
  Activity,
  PieChart
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { Link } from "react-router-dom";

const ReadingDefiMetricsTutorial = () => {
  const [currentStep, setCurrentStep] = useState(1);
  const [completedSteps, setCompletedSteps] = useState<number[]>([]);
  const { toast } = useToast();

  const totalSteps = 6;
  const progress = (currentStep / totalSteps) * 100;

  const steps = [
    {
      id: 1,
      title: "Essential DeFi Metrics",
      icon: BarChart3,
      duration: "5 min",
      content: {
        overview: "Learn the key metrics that determine DeFi protocol health and investment opportunities.",
        coreMetrics: [
          {
            metric: "Total Value Locked (TVL)",
            definition: "Total USD value of assets deposited in a protocol",
            importance: "Indicates protocol size, trust, and network effects",
            calculation: "Sum of all deposited assets at current market prices",
            goodRange: ">$100M for established protocols",
            redFlags: ["Rapid TVL drops", "Artificially inflated TVL", "Single whale dependency"]
          },
          {
            metric: "Volume",
            definition: "Trading volume or transaction value over time period",
            importance: "Shows protocol usage and revenue generation potential",
            calculation: "Sum of transaction values in specified timeframe",
            goodRange: "TVL/Volume ratio between 0.1-10x depending on protocol type",
            redFlags: ["Volume much higher than TVL", "Wash trading", "Bot activity"]
          },
          {
            metric: "Users/Addresses",
            definition: "Number of unique addresses interacting with protocol",
            importance: "Indicates adoption, decentralization, and stickiness",
            calculation: "Count of unique addresses in time period",
            goodRange: ">1000 active users for viable protocols",
            redFlags: ["Few large users", "Declining user count", "Sybil attacks"]
          },
          {
            metric: "Fees Generated",
            definition: "Revenue generated by protocol from users",
            importance: "Shows business model viability and value capture",
            calculation: "Sum of all fees collected over period",
            goodRange: "Sustainable fee generation covering costs",
            redFlags: ["Zero/declining fees", "Unsustainable incentives", "High fee extraction"]
          }
        ],
        protocolSpecificMetrics: [
          {
            protocolType: "Lending Protocols",
            keyMetrics: ["Utilization Rate", "Liquidation Ratio", "Bad Debt", "Interest Rate Spread"],
            healthyRanges: ["70-85% utilization", "<5% liquidations", "Minimal bad debt"]
          },
          {
            protocolType: "DEXes",
            keyMetrics: ["Trading Volume", "Liquidity Depth", "Price Impact", "Market Share"],
            healthyRanges: ["High volume/TVL ratio", "Low slippage", "Growing market share"]
          },
          {
            protocolType: "Yield Farming",
            keyMetrics: ["APY", "Pool Composition", "Impermanent Loss", "Reward Sustainability"],
            healthyRanges: ["Realistic APY", "Balanced pools", "Sustainable rewards"]
          },
          {
            protocolType: "Derivatives",
            keyMetrics: ["Open Interest", "Funding Rates", "Liquidation Engine", "Oracle Quality"],
            healthyRanges: ["Stable funding", "Efficient liquidations", "Reliable oracles"]
          }
        ],
        dataQuality: [
          {
            factor: "Data Sources",
            importance: "Reliable data is crucial for decision making",
            bestPractices: ["Use multiple sources", "Cross-reference data", "Understand methodologies"],
            tools: ["DefiLlama", "DeFiPulse", "Token Terminal", "Dune Analytics"]
          },
          {
            factor: "Time Periods",
            importance: "Metrics can vary significantly over time",
            bestPractices: ["Look at trends, not snapshots", "Consider seasonality", "Use rolling averages"],
            tools: ["Historical data", "Moving averages", "Trend analysis"]
          },
          {
            factor: "Context",
            importance: "Numbers without context can be misleading",
            bestPractices: ["Compare to peers", "Consider market conditions", "Understand business model"],
            tools: ["Competitive analysis", "Market research", "Protocol documentation"]
          }
        ]
      }
    },
    {
      id: 2,
      title: "TVL Analysis Deep Dive",
      icon: DollarSign,
      duration: "6 min",
      content: {
        overview: "Master Total Value Locked analysis to assess protocol strength and identify opportunities.",
        tvlComponents: [
          {
            component: "Native Tokens",
            description: "Protocol's own governance/utility tokens",
            analysisPoints: ["Token concentration", "Vesting schedules", "Utility value"],
            risks: ["Price manipulation", "Governance capture", "Circular value"],
            healthyRange: "<50% of TVL in native tokens"
          },
          {
            component: "Stablecoins",
            description: "USDC, USDT, DAI and other stable assets",
            analysisPoints: ["Stablecoin types", "Depeg risks", "Regulatory risks"],
            risks: ["Centralized stablecoins", "Algorithmic depeg", "Regulatory action"],
            healthyRange: "Mix of different stablecoin types"
          },
          {
            component: "Blue-chip Crypto",
            description: "ETH, WBTC and other established cryptocurrencies",
            analysisPoints: ["Asset diversity", "Correlation risks", "Liquidity"],
            risks: ["High correlation", "Volatile collateral", "Liquidation cascades"],
            healthyRange: "Diversified across multiple assets"
          },
          {
            component: "LP Tokens",
            description: "Liquidity provider tokens from DEXes",
            analysisPoints: ["Underlying asset quality", "Impermanent loss exposure", "Protocol dependencies"],
            risks: ["Nested protocol risks", "IL amplification", "Liquidity withdrawal"],
            healthyRange: "High-quality, liquid LP positions"
          }
        ],
        tvlTrends: [
          {
            trend: "Steady Growth",
            interpretation: "Healthy adoption and confidence",
            lookFor: "Consistent 10-30% monthly growth",
            concerns: "Unsustainable incentives driving growth"
          },
          {
            trend: "Explosive Growth",
            interpretation: "Potential bubble or major catalyst",
            lookFor: ">100% monthly growth",
            concerns: "Mercenary capital, unsustainable yields"
          },
          {
            trend: "Decline",
            interpretation: "Loss of confidence or better alternatives",
            lookFor: ">20% monthly decline",
            concerns: "Fundamental issues, death spiral"
          },
          {
            trend: "Volatility",
            interpretation: "Uncertainty or external factors",
            lookFor: "Large weekly swings >50%",
            concerns: "Unstable user base, external risks"
          }
        ],
        comparativeAnalysis: [
          {
            comparison: "Protocol vs Sector",
            purpose: "Identify relative performance",
            methodology: "Compare TVL growth rates within same category",
            insights: "Market share changes, competitive positioning"
          },
          {
            comparison: "TVL vs Token Price",
            purpose: "Assess value capture",
            methodology: "Plot TVL growth against token performance",
            insights: "Value accrual, market efficiency, fundamentals vs speculation"
          },
          {
            comparison: "TVL vs Revenue",
            purpose: "Evaluate business model efficiency",
            methodology: "Calculate revenue/TVL ratios over time",
            insights: "Capital efficiency, fee extraction, sustainability"
          }
        ],
        redFlags: [
          {
            redFlag: "TVL Concentration",
            description: ">50% TVL from single address/entity",
            implications: "Single point of failure, potential manipulation",
            investigation: "Check address composition, whale watching"
          },
          {
            redFlag: "Circular TVL",
            description: "TVL inflated by protocol's own token staking",
            implications: "Artificial metrics, value illusion",
            investigation: "Break down TVL by asset type"
          },
          {
            redFlag: "Mercenary Capital",
            description: "TVL that disappears when incentives end",
            implications: "Unsustainable model, farmer dumping",
            investigation: "Track TVL vs incentive schedules"
          },
          {
            redFlag: "Cross-Protocol Dependencies",
            description: "Heavy reliance on other protocol's assets",
            implications: "Systemic risk, contagion effects",
            investigation: "Map protocol dependencies"
          }
        ]
      }
    },
    {
      id: 3,
      title: "Revenue & Tokenomics Analysis",
      icon: TrendingUp,
      duration: "6 min",
      content: {
        overview: "Analyze protocol revenue models and tokenomics for sustainable value creation.",
        revenueModels: [
          {
            model: "Transaction Fees",
            description: "Fixed or percentage fees on transactions",
            examples: ["Uniswap 0.3%", "Compound borrowing fees"],
            sustainability: "High - scales with usage",
            analysis: ["Fee levels vs competition", "Volume trends", "User sensitivity"],
            concerns: ["Fee wars", "Volume decline", "Alternative solutions"]
          },
          {
            model: "Spread/Slippage",
            description: "Profit from bid-ask spreads or price impact",
            examples: ["Market makers", "AMM curves", "Orderbook DEXes"],
            sustainability: "Medium - depends on market conditions",
            analysis: ["Spread consistency", "Market efficiency", "Competition"],
            concerns: ["Tightening spreads", "MEV extraction", "Arbitrage"]
          },
          {
            model: "Interest Rate Spreads",
            description: "Difference between borrowing and lending rates",
            examples: ["Aave", "Compound interest margins"],
            sustainability: "High - fundamental banking model",
            analysis: ["Spread stability", "Utilization rates", "Bad debt levels"],
            concerns: ["Rate compression", "Default risk", "Competition"]
          },
          {
            model: "Performance Fees",
            description: "Percentage of profits generated",
            examples: ["Yearn vaults", "Alpha Homora"],
            sustainability: "Variable - depends on performance",
            analysis: ["Fee structure", "Performance consistency", "Benchmark"],
            concerns: ["Poor performance", "Fee sensitivity", "Competition"]
          }
        ],
        tokenomicsEvaluation: [
          {
            element: "Token Distribution",
            analysis: ["Team allocation", "Community allocation", "Vesting schedules"],
            redFlags: [">20% team allocation", "Short vesting", "Immediate unlocks"],
            greenFlags: ["Fair distribution", "Long vesting", "Community focus"]
          },
          {
            element: "Token Utility",
            analysis: ["Governance rights", "Fee discounts", "Staking rewards", "Required for access"],
            redFlags: ["No clear utility", "Governance only", "Artificial requirements"],
            greenFlags: ["Multiple utilities", "Real value accrual", "Network effects"]
          },
          {
            element: "Inflation Schedule",
            analysis: ["Emission rate", "Inflation targeting", "Burn mechanisms"],
            redFlags: ["High inflation", "No burn mechanism", "Uncapped supply"],
            greenFlags: ["Controlled inflation", "Deflationary mechanics", "Sustainable rewards"]
          },
          {
            element: "Value Accrual",
            analysis: ["Revenue sharing", "Buybacks", "Fee burning", "Stake requirements"],
            redFlags: ["No value accrual", "Pure governance", "High dilution"],
            greenFlags: ["Clear value capture", "Fee sharing", "Deflationary pressure"]
          }
        ],
        sustainabilityMetrics: [
          {
            metric: "Revenue/Token Inflation",
            calculation: "Protocol Revenue / Token Inflation Cost",
            interpretation: ">1 means revenue covers inflation",
            target: ">2x for sustainable models",
            implications: "Ability to reduce incentives over time"
          },
          {
            metric: "Revenue per User",
            calculation: "Total Revenue / Active Users",
            interpretation: "Revenue efficiency per user",
            target: "Growing over time",
            implications: "User value and monetization effectiveness"
          },
          {
            metric: "Token Velocity",
            calculation: "Volume / Market Cap",
            interpretation: "How often tokens change hands",
            target: "Moderate velocity (not too high)",
            implications: "Token holding incentives and value capture"
          },
          {
            metric: "Protocol Owned Liquidity",
            calculation: "Protocol-owned assets / Total TVL",
            interpretation: "Independence from mercenary capital",
            target: ">20% for mature protocols",
            implications: "Sustainability and independence"
          }
        ],
        competitiveAnalysis: [
          {
            dimension: "Market Share",
            metrics: ["TVL share", "Volume share", "User share"],
            analysis: "Trends over time, growth vs competitors",
            insights: "Competitive positioning and moats"
          },
          {
            dimension: "Efficiency Ratios",
            metrics: ["Revenue/TVL", "Volume/TVL", "Users/TVL"],
            analysis: "Compare efficiency across similar protocols",
            insights: "Operational excellence and business model"
          },
          {
            dimension: "Innovation Pace",
            metrics: ["Feature releases", "Integrations", "Partnerships"],
            analysis: "Development activity and ecosystem growth",
            insights: "Long-term competitive advantage"
          }
        ]
      }
    },
    {
      id: 4,
      title: "User & Activity Metrics",
      icon: Users,
      duration: "5 min",
      content: {
        overview: "Understand user behavior and protocol adoption through activity metrics.",
        userMetrics: [
          {
            metric: "Daily Active Users (DAU)",
            definition: "Unique addresses interacting with protocol daily",
            importance: "Shows current adoption and engagement",
            calculation: "Count unique addresses per day",
            benchmarks: ["DeFi protocols: 100-10,000+", "Major protocols: >1,000"],
            trends: "Look for consistent growth or stable high numbers"
          },
          {
            metric: "Monthly Active Users (MAU)",
            definition: "Unique addresses interacting with protocol monthly",
            importance: "Shows broader user base and retention",
            calculation: "Count unique addresses per month",
            benchmarks: ["Growing protocols: 1,000-100,000+"],
            trends: "Should be 10-30x DAU for healthy engagement"
          },
          {
            metric: "User Retention Rate",
            definition: "Percentage of users who return after first interaction",
            importance: "Indicates product-market fit and stickiness",
            calculation: "Returning users / Total new users",
            benchmarks: ["Good DeFi: >20% monthly retention"],
            trends: "Higher retention in bear markets indicates strength"
          },
          {
            metric: "User Concentration",
            definition: "Distribution of activity among users",
            importance: "Shows decentralization and dependency risk",
            calculation: "Gini coefficient or top 10% user activity share",
            benchmarks: ["Healthy: <50% activity from top 10% users"],
            trends: "Decreasing concentration over time is positive"
          }
        ],
        activityPatterns: [
          {
            pattern: "Transaction Frequency",
            analysis: ["Transactions per user", "Average session length", "Return frequency"],
            insights: "User engagement depth and protocol utility",
            healthySignals: ["Regular usage patterns", "Multi-transaction sessions"]
          },
          {
            pattern: "Value per Transaction",
            analysis: ["Average transaction size", "Distribution of transaction sizes"],
            insights: "User sophistication and use case validation",
            healthySignals: ["Diverse transaction sizes", "Growing average values"]
          },
          {
            pattern: "Geographic Distribution",
            analysis: ["User location diversity", "Regulatory concentration risk"],
            insights: "Market penetration and regulatory risk",
            healthySignals: ["Global distribution", "No single country dominance"]
          },
          {
            pattern: "User Journey Analysis",
            analysis: ["Entry points", "Feature adoption", "Exit patterns"],
            insights: "User experience and product-market fit",
            healthySignals: ["Multi-feature usage", "Natural progression"]
          }
        ],
        cohortAnalysis: [
          {
            cohortType: "Monthly Cohorts",
            purpose: "Track user retention over time",
            methodology: "Group users by first interaction month, track retention",
            insights: "Product improvements, market conditions impact",
            actionItems: "Identify high-retention periods and replicate"
          },
          {
            cohortType: "Value Cohorts",
            purpose: "Analyze behavior by user value",
            methodology: "Group users by transaction volume, analyze patterns",
            insights: "Whale vs retail behavior, value distribution",
            actionItems: "Optimize for different user segments"
          },
          {
            cohortType: "Feature Cohorts",
            purpose: "Compare users by feature adoption",
            methodology: "Group by feature usage, compare outcomes",
            insights: "Feature value and user lifecycle",
            actionItems: "Improve feature onboarding and education"
          }
        ],
        qualityMetrics: [
          {
            metric: "Organic vs Incentivized Usage",
            measurement: "Activity before/after incentive programs",
            importance: "Distinguishes real demand from farmer activity",
            analysis: "Compare user behavior in different incentive periods",
            redFlags: ["Activity drops dramatically when incentives end"]
          },
          {
            metric: "Bot vs Human Activity",
            measurement: "Pattern analysis and behavior classification",
            importance: "Ensures metrics reflect genuine adoption",
            analysis: "Look for repetitive patterns, MEV activity, arbitrage",
            redFlags: ["High percentage of automated/bot activity"]
          },
          {
            metric: "Sybil Resistance",
            measurement: "Address clustering and identity analysis",
            importance: "Prevents manipulation of user metrics",
            analysis: "Cluster addresses by behavior and funding sources",
            redFlags: ["Many addresses with similar patterns/funding"]
          }
        ],
        userSegmentation: [
          {
            segment: "Whales",
            definition: "Users with >$100k in protocol",
            characteristics: ["High transaction values", "Complex strategies", "Price sensitive"],
            importance: "Drive most volume and TVL",
            risks: "High concentration, potential for manipulation"
          },
          {
            segment: "Power Users",
            definition: "Regular users with $1k-100k",
            characteristics: ["Frequent usage", "Multiple features", "Community active"],
            importance: "Core user base, network effects",
            risks: "May migrate to better opportunities"
          },
          {
            segment: "Retail Users",
            definition: "Occasional users with <$1k",
            characteristics: ["Simple strategies", "Price sensitive", "Education needs"],
            importance: "Growth potential, decentralization",
            risks: "High churn, low revenue per user"
          }
        ]
      }
    },
    {
      id: 5,
      title: "Risk Assessment Metrics",
      icon: Shield,
      duration: "5 min",
      content: {
        overview: "Evaluate protocol risks through quantitative metrics and qualitative analysis.",
        technicalRisks: [
          {
            risk: "Smart Contract Risk",
            metrics: ["Code audit scores", "Bug bounty programs", "Time since deployment"],
            measurement: ["Audit coverage", "Critical bugs found", "Developer activity"],
            mitigation: ["Multiple audits", "Formal verification", "Bug bounties", "Time-testing"],
            redFlags: ["No audits", "Recent critical bugs", "Complex unaudited code"]
          },
          {
            risk: "Oracle Risk",
            metrics: ["Oracle decentralization", "Price deviation events", "Update frequency"],
            measurement: ["Number of oracle sources", "Historical price accuracy", "Latency"],
            mitigation: ["Multiple oracle providers", "Circuit breakers", "Median pricing"],
            redFlags: ["Single oracle", "Frequent deviations", "Centralized price feeds"]
          },
          {
            risk: "Governance Risk",
            metrics: ["Token concentration", "Voter participation", "Proposal success rates"],
            measurement: ["Gini coefficient", "Governance participation", "Decision speed"],
            mitigation: ["Distributed governance", "Time delays", "Veto mechanisms"],
            redFlags: ["Whale control", "Low participation", "Rushed decisions"]
          },
          {
            risk: "Economic Risk",
            metrics: ["Token inflation", "Revenue sustainability", "Liquidity ratios"],
            measurement: ["Inflation rate", "Revenue/costs", "Available liquidity"],
            mitigation: ["Controlled inflation", "Revenue diversification", "Liquidity buffers"],
            redFlags: ["High inflation", "Unsustainable economics", "Liquidity crunches"]
          }
        ],
        liquidityRisks: [
          {
            aspect: "Withdrawal Liquidity",
            measurement: "Available assets vs potential withdrawals",
            calculation: "Free liquidity / Total user deposits",
            healthyRange: ">20% available liquidity",
            monitoring: "Daily tracking during volatile periods"
          },
          {
            aspect: "Market Liquidity",
            measurement: "Trading liquidity for protocol tokens",
            calculation: "Daily volume / Market cap",
            healthyRange: ">5% daily turnover",
            monitoring: "Token liquidity and slippage tracking"
          },
          {
            aspect: "Collateral Liquidity",
            measurement: "Liquidity of accepted collateral assets",
            calculation: "Collateral trading volume and depth",
            healthyRange: "High liquidity for major collateral",
            monitoring: "Collateral market conditions"
          }
        ],
        concentrationRisks: [
          {
            type: "User Concentration",
            measurement: "Top user share of TVL/volume",
            calculation: "Top 10 users / Total TVL",
            riskLevel: "High if >50%",
            mitigation: "User diversification incentives"
          },
          {
            type: "Asset Concentration",
            measurement: "Single asset share of collateral",
            calculation: "Largest asset / Total collateral",
            riskLevel: "High if >70%",
            mitigation: "Asset diversification requirements"
          },
          {
            type: "Geographic Concentration",
            measurement: "Single jurisdiction user concentration",
            calculation: "Largest jurisdiction / Total users",
            riskLevel: "High if >60%",
            mitigation: "Global user acquisition"
          }
        ],
        systemicRisks: [
          {
            risk: "Correlation Risk",
            description: "High correlation between protocol assets",
            measurement: "Asset price correlations, shared dependencies",
            monitoring: "Correlation matrices, dependency mapping",
            mitigation: "Diversification requirements, correlation limits"
          },
          {
            risk: "Contagion Risk",
            description: "Risk spillover from connected protocols",
            measurement: "Integration depth, shared infrastructure",
            monitoring: "Protocol dependency graphs, failure scenarios",
            mitigation: "Isolation mechanisms, circuit breakers"
          },
          {
            risk: "Regulatory Risk",
            description: "Regulatory action affecting protocol",
            measurement: "Regulatory clarity, compliance status",
            monitoring: "Legal developments, compliance metrics",
            mitigation: "Regulatory compliance, geographic diversification"
          }
        ],
        riskScoring: [
          {
            category: "Technical Risk",
            weight: "30%",
            factors: ["Audit quality", "Code complexity", "Time in operation"],
            scoring: "1-10 scale based on objective criteria"
          },
          {
            category: "Economic Risk",
            weight: "25%",
            factors: ["Revenue sustainability", "Token economics", "Market conditions"],
            scoring: "1-10 scale based on financial metrics"
          },
          {
            category: "Governance Risk",
            weight: "20%",
            factors: ["Decentralization", "Participation", "Decision quality"],
            scoring: "1-10 scale based on governance metrics"
          },
          {
            category: "Operational Risk",
            weight: "15%",
            factors: ["Team quality", "Development activity", "Community"],
            scoring: "1-10 scale based on operational metrics"
          },
          {
            category: "External Risk",
            weight: "10%",
            factors: ["Regulatory environment", "Market conditions", "Competition"],
            scoring: "1-10 scale based on external factors"
          }
        ]
      }
    },
    {
      id: 6,
      title: "Metrics Integration & Decision Making",
      icon: Activity,
      duration: "6 min",
      content: {
        overview: "Combine multiple metrics for comprehensive protocol evaluation and investment decisions.",
        holisticFramework: [
          {
            dimension: "Growth Stage Analysis",
            early: {
              keyMetrics: ["User growth rate", "Feature development", "Team quality"],
              expectedPatterns: ["Rapid user growth", "High volatility", "Limited revenue"],
              riskFactors: ["Execution risk", "Product-market fit", "Competition"],
              allocation: "5-10% of portfolio"
            },
            growth: {
              keyMetrics: ["Market share growth", "Revenue growth", "Ecosystem development"],
              expectedPatterns: ["Consistent growth", "Improving metrics", "Scaling challenges"],
              riskFactors: ["Scaling issues", "Competition", "Market saturation"],
              allocation: "10-20% of portfolio"
            },
            mature: {
              keyMetrics: ["Market position", "Profitability", "Dividend/yield"],
              expectedPatterns: ["Stable metrics", "Predictable performance", "Value focus"],
              riskFactors: ["Disruption", "Regulation", "Innovation lag"],
              allocation: "20-40% of portfolio"
            }
          }
        ],
        decisionMatrix: [
          {
            scenario: "High TVL Growth + High User Growth",
            interpretation: "Strong adoption and network effects",
            actionItems: ["Increase allocation", "Monitor sustainability", "Track competition"],
            riskFactors: ["Unsustainable incentives", "Bubble formation", "Capacity constraints"]
          },
          {
            scenario: "High TVL + Low User Growth",
            interpretation: "Whale concentration or incentive farming",
            actionItems: ["Investigate user composition", "Monitor for risks", "Consider reduced allocation"],
            riskFactors: ["Whale dependency", "Artificial metrics", "Sustainability issues"]
          },
          {
            scenario: "Low TVL + High User Growth",
            interpretation: "Early adoption or retail focus",
            actionItems: ["Monitor monetization", "Track user retention", "Assess scaling"],
            riskFactors: ["Monetization challenges", "Scaling issues", "Competition"]
          },
          {
            scenario: "Declining Metrics Across Board",
            interpretation: "Fundamental issues or market conditions",
            actionItems: ["Investigate causes", "Reduce allocation", "Monitor for recovery"],
            riskFactors: ["Death spiral", "Structural problems", "Market rejection"]
          }
        ],
        portfolioIntegration: [
          {
            principle: "Correlation Analysis",
            implementation: "Analyze metric correlations across portfolio",
            purpose: "Identify systemic risks and diversification opportunities",
            tools: ["Correlation matrices", "Factor analysis", "Stress testing"]
          },
          {
            principle: "Risk Budgeting",
            implementation: "Allocate based on risk-adjusted returns",
            purpose: "Optimize portfolio risk vs return profile",
            tools: ["Sharpe ratio analysis", "Risk parity", "Monte Carlo simulation"]
          },
          {
            principle: "Dynamic Allocation",
            implementation: "Adjust allocations based on metric changes",
            purpose: "Capture opportunities and manage risks dynamically",
            tools: ["Automated rebalancing", "Alert systems", "Scenario analysis"]
          }
        ],
        monitoringSystem: [
          {
            frequency: "Real-time",
            metrics: ["Price movements", "Large transactions", "System alerts"],
            tools: ["Price feeds", "Whale watching", "Protocol status"],
            actions: ["Emergency response", "Opportunity capture", "Risk management"]
          },
          {
            frequency: "Daily",
            metrics: ["TVL changes", "Volume patterns", "User activity"],
            tools: ["Dashboard monitoring", "Trend analysis", "Comparative tracking"],
            actions: ["Portfolio adjustments", "Research updates", "Strategy refinement"]
          },
          {
            frequency: "Weekly",
            metrics: ["Comprehensive performance", "Risk assessment", "Competitive analysis"],
            tools: ["Performance reports", "Risk dashboards", "Market analysis"],
            actions: ["Strategy review", "Allocation adjustments", "Research planning"]
          },
          {
            frequency: "Monthly",
            metrics: ["Full portfolio review", "Market positioning", "Strategic planning"],
            tools: ["Performance attribution", "Strategy backtesting", "Scenario planning"],
            actions: ["Major decisions", "Strategy overhaul", "Long-term planning"]
          }
        ],
        automationOpportunities: [
          {
            area: "Alert Systems",
            automation: "Automated alerts for metric thresholds",
            benefits: ["Faster response", "Consistent monitoring", "Reduced workload"],
            implementation: "Set up alerts for key metric changes"
          },
          {
            area: "Data Collection",
            automation: "Automated data gathering and processing",
            benefits: ["Accurate data", "Time savings", "Comprehensive coverage"],
            implementation: "APIs, web scraping, database automation"
          },
          {
            area: "Analysis",
            automation: "Automated analysis and reporting",
            benefits: ["Consistent analysis", "Pattern recognition", "Scalability"],
            implementation: "Machine learning, statistical analysis, dashboard automation"
          },
          {
            area: "Execution",
            automation: "Automated trading based on metrics",
            benefits: ["Discipline", "Speed", "Emotion-free decisions"],
            implementation: "Trading bots, smart contracts, DeFi automation"
          }
        ]
      }
    }
  ];

  const currentStepData = steps.find(step => step.id === currentStep);

  const handleNext = () => {
    if (currentStep < totalSteps) {
      setCompletedSteps(prev => [...prev, currentStep]);
      setCurrentStep(currentStep + 1);
    } else {
      setCompletedSteps(prev => [...prev, currentStep]);
      
      // Save completion to localStorage
      const completed = JSON.parse(localStorage.getItem('completedTutorials') || '[]');
      if (!completed.includes('risk-assessment')) {
        completed.push('risk-assessment');
        localStorage.setItem('completedTutorials', JSON.stringify(completed));
      }
      
      toast({
        title: "Tutorial Complete! 🎉",
        description: "Well done! You can now analyze DeFi metrics like a pro.",
      });
      setTimeout(() => {
        window.location.href = "/tutorials?tab=practical";
      }, 1500);
    }
  };

  const handlePrevious = () => {
    if (currentStep > 1) {
      setCurrentStep(currentStep - 1);
    }
  };

  const handleStepComplete = () => {
    setCompletedSteps(prev => [...prev, currentStep]);
    toast({
      title: "Step completed!",
      description: `You've completed step ${currentStep}: ${currentStepData?.title}`,
    });
  };

  const isStepCompleted = (stepId: number) => completedSteps.includes(stepId);

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-muted">
      <div className="container mx-auto px-4 py-8 mobile-typography-center">
        {/* Back to Tutorials Button */}
        <div className="mb-6">
          <Link to="/tutorials">
            <Button variant="ghost" className="gap-2 hover:bg-muted">
              <ArrowLeft className="h-4 w-4" />
              Back to Tutorials
            </Button>
          </Link>
        </div>

        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2 rounded-lg bg-primary/10">
              <BarChart3 className="h-6 w-6 text-primary" />
            </div>
            <div>
              <h1 className="text-3xl font-bold">Reading DeFi Metrics</h1>
              <p className="text-muted-foreground">Master data-driven DeFi investment decisions</p>
            </div>
          </div>

          {/* Progress */}
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <span>Step {currentStep} of {totalSteps}</span>
              <span>{Math.round(progress)}% Complete</span>
            </div>
            <Progress value={progress} className="h-2" />
          </div>
        </div>

        {/* Step Navigation */}
        <div className="flex flex-wrap gap-2 mb-8">
          {steps.map((step) => {
            const StepIcon = step.icon;
            const completed = isStepCompleted(step.id);
            const current = step.id === currentStep;
            
            return (
              <Button
                key={step.id}
                variant={current ? "default" : completed ? "secondary" : "outline"}
                size="sm"
                onClick={() => setCurrentStep(step.id)}
                className={`flex items-center gap-2 ${completed ? "bg-awareness/10 text-awareness hover:bg-awareness/20 border-awareness" : ""}`}
              >
                <StepIcon className="h-4 w-4" />
                <span className="hidden sm:inline">{step.title}</span>
                <span className="sm:hidden">{step.id}</span>
                {completed && <CheckCircle className="h-3 w-3" />}
              </Button>
            );
          })}
        </div>

        {/* Current Step Content */}
        {currentStepData && (
          <Card className="mb-8">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg bg-primary/10">
                    <currentStepData.icon className="h-5 w-5 text-primary" />
                  </div>
                  <div>
                    <CardTitle>{currentStepData.title}</CardTitle>
                    <CardDescription>
                      Estimated time: {currentStepData.duration}
                    </CardDescription>
                  </div>
                </div>
                <Badge variant={isStepCompleted(currentStep) ? "default" : "secondary"}>
                  {isStepCompleted(currentStep) ? "Completed" : "In Progress"}
                </Badge>
              </div>
            </CardHeader>

            <CardContent className="space-y-6">
              <p className="text-muted-foreground">{currentStepData.content.overview}</p>

              {/* Content implementation would go here */}

              {/* Step Navigation */}
              <div className="flex items-center justify-between pt-6 border-t">
                <Button
                  variant="outline"
                  onClick={handlePrevious}
                  disabled={currentStep === 1}
                >
                  <ArrowLeft className="h-4 w-4 mr-2" />
                  Previous
                </Button>

                <div className="flex gap-2">
                  {!isStepCompleted(currentStep) && (
                    <Button
                      variant="secondary"
                      onClick={handleStepComplete}
                    >
                      <CheckCircle className="h-4 w-4 mr-2" />
                      Mark Complete
                    </Button>
                  )}
                  
                  <Button
                    onClick={handleNext}
                  >
                    {currentStep === totalSteps ? "Finish Tutorial" : "Next Step"}
                    <ArrowRight className="h-4 w-4 ml-2" />
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Completion Message */}
        {completedSteps.length === totalSteps && (
          <Card className="bg-awareness/10 border-awareness/20">
            <CardHeader>
              <CardTitle className="text-awareness flex items-center gap-2">
                <CheckCircle className="h-6 w-6" />
                DeFi Metrics Analysis Mastery Complete!
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-foreground mb-4">
                You can now analyze DeFi protocols using data-driven metrics and make informed investment decisions!
              </p>
              <div className="flex gap-2">
                <Button asChild>
                  <Link to="/tutorials">Back to Tutorials</Link>
                </Button>
                <Button variant="outline" asChild>
                  <Link to="/courses">Continue Learning</Link>
                </Button>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
};

export default ReadingDefiMetricsTutorial;